version: '3.8'

services:
  app:
    image: node:22
    container_name: nelo-dining
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    environment:
      - SERVER_PORT=4000
      - DATABASE_URL=postgres://postgres:password@db:5432/pg-dining
    command: >
      sh -c "npm clean && npm run start"
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: pg-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pg-dining
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/clean-db.sql
volumes:
  pg_data: